### ISSUE TITLE
Could you please share the training dataset?

### ISSUE THREAD

**Issue by yuqing-liu-dut** [kbzhang0505/JNSFANet#1]
Amazing work. Could you please share the training data? I cannot find it in your repo.

**Comment by Gray-OREO** [comment]
1. Ma C., Yang C. Y., Yang X., Yang M. H.: Learning a no-reference quality metric for single-image super-resolution. Computer Vision and Image Understanding. 158, 1-16 (2017)

2. Zhou F., Yao R., Liu B., Qiu G.: Visual quality assessment for super-resolved images: Database and method. IEEE Transactions on Image Processing. 28(7), 3528-3541 (2019)

I'm sorry for the late reply. The above papers may help you by the download links or get the database by contacting the authors.
